# 12 Tidy data

[Confira o livro neste link](https://r4ds.had.co.nz/tidy-data.html)

### Prerequisites (12.1.1)

```{r message=FALSE, warning=FALSE}
# library(tidyverse)
library(dados)
library(ggplot2)
library(magrittr)
library(dplyr)
library(tidyr)
```

## Tidy data (12.2)

```{r}
tabela1

tabela2

tabela3

# Spread across two tibbles

tabela4a  # casos

tabela4b  # população
```

```{r}
# Calcule a taxa por 10.000 pessoas

tabela1 %>% 
  mutate(taxa = casos / populacao * 10000)
```

```{r}
# Calcule casos por ano

tabela1 %>% 
  count(ano, wt = casos)
```

```{r}
ggplot(tabela1, aes(ano, casos)) + 
  geom_line(aes(group = pais), colour = "grey50") + 
  geom_point(aes(colour = pais))
```

## Pivoting (12.3)

### Longer (12.3.1)


```{r}
tabela4a
```

```{r}
tabela4a %>%
  pivot_longer(c(`1999`, `2000`), names_to = "ano", values_to = "casos")
```

```{r}
tabela4b %>% 
  pivot_longer(c(`1999`, `2000`), names_to = "ano", values_to = "populacao")
```


```{r}
tidy4a <- tabela4a %>% 
  pivot_longer(c(`1999`, `2000`), names_to = "ano", values_to = "casos")

tidy4b <- tabela4b %>% 
  pivot_longer(c(`1999`, `2000`), names_to = "ano", values_to = "populacao")


left_join(tidy4a, tidy4b)
```


### Wider (12.3.2)

```{r}
tabela2
```

```{r}
tabela2 %>%
    pivot_wider(names_from = tipo, values_from = contagem)
```

## Separating and uniting (12.4)

### Separate (12.4.1)

```{r}
tabela3
```

```{r}
tabela3 %>% 
  separate(taxa, into = c("casos", "populacao"))
```

```{r}
tabela3 %>% 
  separate(taxa, into = c("casos", "populacao"), sep = "/")
```


```{r}
tabela3 %>% 
  separate(taxa, into = c("casos", "populacao"), convert = TRUE)
```


```{r}
tabela3 %>% 
  separate(ano, into = c("seculo", "ano"), sep = 2)
```

### Unite (12.4.2)

```{r}
tabela5 %>% 
  unite(novo, seculo, ano)
```

```{r}
tabela5 %>% 
  unite(novo, seculo, ano, sep = "")
```


## Case Study (12.6)

```{r}
dados_oms
```

```{r}
dados_oms1 <- dados_oms %>%  #Problema aqui! Porque nossa base tem 1 coluna a menos?
  pivot_longer(
    cols = novos_fpp_h014:novos_recaida_m65, 
    names_to = "chave", 
    values_to = "casos", 
    values_drop_na = TRUE
  )
dados_oms1
```

```{r}
dados_oms1 %>% 
  count(chave)
```

```{r}
dados_oms2 <- dados_oms1 %>% 
  # Precisa substituir o newrel - qual seria o equivalente?
  mutate(chave = stringr::str_replace(chave, "newrel", "new_rel"))
dados_oms2
```

```{r}
dados_oms3 <- dados_oms2 %>% 
  separate(chave, c("novos", "tipo", "sexo_faixa_etaria"), sep = "_")
dados_oms3
```

```{r}
dados_oms3 %>% 
  count(novos)

dados_oms4 <- dados_oms3 %>% 
  select(-novos, -iso2, -iso3)
```

```{r}
dados_oms5 <- dados_oms4 %>% 
  separate(sexo_faixa_etaria, c("sexo", "faixa_etaria"), sep = 1)
dados_oms5
```

```{r}
dados_oms %>%
  pivot_longer(
    cols = novos_fpp_h014:novos_recaida_m65, 
    names_to = "chave", 
    values_to = "casos", 
    values_drop_na = TRUE
  ) %>% 
  mutate(
    # Como alterar a linha abaixo?
    chave = stringr::str_replace(chave, "newrel", "new_rel")
  ) %>%
  separate(chave, c("novos", "tipo", "sexo_faixa_etaria")) %>% 
  select(-novos, -iso2, -iso3) %>% 
  separate(sexo_faixa_etaria, c("sexo", "faixa_etaria"), sep = 1)
```

